forgejo:
    gitea:
        admin:
            username: ENC[AES256_GCM,data:c1lgoRTEUvcN,iv:1nMKAotJJi0dclVBVQJXKpJsntcMRMdN9tQVxv6vy/c=,tag:p32AETD2F033uQFIKjhOzQ==,type:str]
            password: ENC[AES256_GCM,data:REcc8dJbDhLhq1q+ObWIUitORGpHsRCfJ9QW,iv:PAoj2pvTJqpObD84Q1Es1UAI/mDjcJD4cW2s6U2Akyc=,tag:xxH8Yo76CH7eZKG9ZDgaqg==,type:str]
            email: ENC[AES256_GCM,data:Jrs92fhN0IAmMivN0fIGxtz8+UIkmQ==,iv:qnVvCkA3eICp2+F4KcYNQoiBViPc3dpCnPYAmzw5b4U=,tag:H4ZO01RW0Z4Hz9SD8EkrNA==,type:str]
sops:
    age:
        - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZXo0ZTVLN1RieFdDbFVR
            SEVUUFd3T2NGREVoOC9HTloxemxZMTFFS2swCi9nbFRGQ2pJQWVKNUY2VTFPSDh1
            UjlWUXdHUjY0TGl1dkRURnV4TXoyQTgKLS0tIC9UdjlLUHJ4RWcrb21hMUlxUmg4
            cHU0bnFLbGR4bFBHQ0pIZHVJSTJXYWsKU3vGFkXdtWusZwnHp5ZKXOu0obSjY7xU
            j6eI72NVaoPWbVb+B5Wv9bTQDIYTN4MaR9maVoBMPASPufFuuwmLIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T13:47:08Z"
    mac: ENC[AES256_GCM,data:oy+mjWVkBen4Zp16sAXSWdqQKJxf7feAkiDiff5riIYsTv/ZNO5ybZ0STE4SJGakGBhbEGYObeKmKFxhs9U2cO5vMzcTPzgyN5piKvd3FA4gRIv0SjGSXejgCDsV4+V7Su70emXvMr0A7Xr8iRAdLxmA+Xro10cMakWDQwNjn2s=,iv:HNBDKw20JfNAw7cB5F923I/3gf2kfiH5IutJImnf4Z0=,tag:b5CAfAFu93LiJ5+RAxbJWw==,type:str]
    encrypted_regex: ^(secrets|.*)$
    version: 3.11.0
