secrets:
    secret-forgejo-username: ENC[AES256_GCM,data:1GKJhRU=,iv:zXa+yYcOnG23bN8WoKXa1+va4Xv7LhcZMPLpZnZtQr0=,tag:uFnSPgNtpKxhYXGXjOiQLA==,type:str]
    secret-forgejo-password: ENC[AES256_GCM,data:b20p//ULbiZtHN+yteii,iv:3qaPPvo3ze2iRdOIUKUAaHG8vAluc/S0xQrz+6t4q/I=,tag:pwWLb+lKpAnD+wn19ZQSIA==,type:str]
    secret-forgejo-email: ENC[AES256_GCM,data:JEiyc/o5uNm1+rR6LF6FURbhYevxUg==,iv:eYvscBwcxvyTW4OZhF/fzn1/z87NtbA7Ll3JIhB0qQY=,tag:7CWi3gwPDLO+L/fVlgswhQ==,type:str]
sops:
    age:
        - recipient: age14x7jgxf0t2dfmquw6cenec5c7lqryzcvd0cxv85xlwtzafdcr9eql0vmm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVR4KzhheFNyc2ozZU83
            dkc1ZytSY2pDOWNiMWdEcWVNZWJ2ZDhEL3g4CkViSEtLYkhYUlRUK1p2TGFzNTZ6
            V0ErdkwvSytKSC9BMHcvZWFRVWdyNlkKLS0tIENDS0E1RWZoK2VkdHpxckhBQm9x
            RytHelNTRUU5aklHZDRPQXJJTCtlNTAK8vrgIiM+WUdUzPW8JPU9gGVWC7FTXo6/
            apTg/XmNd/L1JFO6vjYJSHFEu6ARdKDLs3BE0ReVKPad3VKJ5j2RUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T09:36:31Z"
    mac: ENC[AES256_GCM,data:Z25uiBE2OOUBvgmc66uCPk8LX4C1lVQg+ae412cAue47jlate2OUip17Y6vexGke2VtDF9Ol1W6Ywe+O9pSTYRodkceY3c4DR6geg+mYV0TpRdqCwKfaKL8Uv0Q7hyNdQdmuwQRVG+dIvMwz1kGxGIs4R//BHejC1XhD+q/Ejgc=,iv:wQSk0lz5SkxxR8uWpKFEgC++Z0iRb/n/C+AC7QkBMow=,tag:QRR/ClfBJnXhz3t7NkKWZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
