secrets:
    forgejo-username:
        username: ENC[AES256_GCM,data:85Uc0e0=,iv:t5lIcl7sx3nww4g7jwYqa5nPZLEGn1ilZcmn9PG1/3c=,tag:DMN6HosuRJigOAmKu5YSQw==,type:str]
    forgejo-password:
        password: ENC[AES256_GCM,data:3eZwVH02GFEjStAVf9L6,iv://+srTBtS3WOtmF9cxebm7XldIVvSV90guBNM1StISo=,tag:Q2oygKEqDOokJcRQpGiaeQ==,type:str]
    forgejo-email:
        email: ENC[AES256_GCM,data:ejbPEPoj/RxscvVnbPopAznQJKmgPA==,iv:zyD7gOVI/m7VVK+ygYVPbhNkXlvGrj8sclGAMu7U4Fg=,tag:g+7lr8VotdiEoNPPHGqwDQ==,type:str]
sops:
    age:
        - recipient: age14x7jgxf0t2dfmquw6cenec5c7lqryzcvd0cxv85xlwtzafdcr9eql0vmm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTnFGamdyb2paRzJSTlNr
            MGx0RDJIUnI0bDgxNzVwbGZscThTMytZWFVvCnoyWFlWWlpvU2dKMk1yRU5Vd1kv
            OFRCdm9OaXF6aVVmVHh2a0tJQ3hLSEUKLS0tIGorVlU3NjVROHdCR2JSUTBPV21v
            TDRlSVRIZkYwWHBIcEk0Z2FZSXVVMDgKlC8S/0u/hCj9zcUF7uBIX1rgGG0NRszH
            h3/WZGrRls9n4K/BwKPz1O7361fZmb7ZHQADRynm5WFFWQL+DQNngA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T11:57:40Z"
    mac: ENC[AES256_GCM,data:7PGXg56fIdVYXWdM11bKUMMPA9WxDePCoFr/CnaJUeCjkqjzeW/Pbpno8LNOuPEolgZrPyzTC7V82lHrxhgtkwQUu312DBO6FdHyJIKGskXt+pWdKLVZh0JGbj4DHs9sD8p1pyev/C0JQEQ4HomCAbaD7EfUh4uXEfJuTDd7hTE=,iv:gStpCAtmP73hek/Qq+JUL0ay2wnB4fEgrUxP2DNg3Kw=,tag:h1KYoehkKTXpGTYqZBigvA==,type:str]
    encrypted_regex: ^(secrets|.*)$
    version: 3.11.0
