forgejo:
  gitea:
    admin:
      username: ENC[AES256_GCM,data:hSoDlnQ=,iv:Xjj7gJP8bRkUU9RewLdcYmvttrFEGPOJgNEuW0ht5vE=,tag:CV0i1LYWvvxkFbmuhG7A4w==,type:str]
      password: ENC[AES256_GCM,data:Sjfz4BzOPSpldcBsQ2pgew==,iv:n/U+nGE7FqHS6XZ8kDltRfaC5mI1MEH4zZocO0WoUjM=,tag:1xR08gTKzWAaXe4k0Atwig==,type:str]
      email: ENC[AES256_GCM,data:SvVkYg2ZL4YD4db6+W56tS0UqHrbTQ==,iv:HmFcwEYwCVMs9Qiv4jIv9ot4q3liG5Rr2fxSCGXgcKw=,tag:pAVDtUC/TU/OjThmzCvz0A==,type:str]
sops:
  age:
    - recipient: age14x7jgxf0t2dfmquw6cenec5c7lqryzcvd0cxv85xlwtzafdcr9eql0vmm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMHFzRkFEVGdMUGYrWThJ
        RUx4MjJ0bXpDNHVnY3lpRjZNYlRnQTBGTGd3CnBCNU1OaHQ1MDYxYTU5OVF1NHp3
        NGtKbzBmTUx1RVZrN2d3QXZPSW0vV0kKLS0tIHBUbG9IM3F0eTVXaHhyWTR6SkN1
        Z0Y5NjVZeXh5ei9aaTVIcVVQOXQ5cmcKqhEd0I2dHkBqiOdjBhhonINEQTwtgTpT
        B0w1v3e44TJTle8MDqQYt+UTX6E73zvK0yNC3xOiNwF+xLemmUFipw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T11:43:37Z"
  mac: ENC[AES256_GCM,data:apAquX8+m5RLzPBeGkvK9eSc4EznfYuZu7cfYR6copHifraIWhKpxFQ/1rZs19blbmdZ81UIbRoSRVKDjbzc/WNx0YBmEWEb2dKQa7fZlmuXM+lmqqWJqxJaHmUAiDStwOAJPHNcQ87IHUVkmKhPzOheWj4lpWOReOawVnn7pC4=,iv:8856nzbuPTX8tflNhtNIMHEFkmwokI5lhPJ8aG5lbgc=,tag:TYFFJ5KCGC4ut9hIjnjwrA==,type:str]
  encrypted_regex: ^(secrets|.*)$
  version: 3.11.0