secrets:
    forgejo-admin:
        username: ENC[AES256_GCM,data:PWb929Y=,iv:vF/+o9t7VkjRe+RbiZujRSj97r1uBPZ2BwbEMCccwhY=,tag:zrVkdzp7v5e5rc9KHGmxbQ==,type:str]
        password: ENC[AES256_GCM,data:2Co76VJeSMc7L4LjohWe,iv:cirX92wn/3mcAkd6VVbu2qHYF/8aivvG0rRFZICKWEU=,tag:uQ6qQ5DKy6dCz4vzEIP3ZA==,type:str]
        email: ENC[AES256_GCM,data:jK4U7vlngO3sg7gZ6ibJtPFTcBhSyg==,iv:ByToAggbXyr9xxfjzV548gePjrXA7UOxkaSTrb9wAlc=,tag:7fYOTkRZYYTG84VS5pRe8g==,type:str]
sops:
    age:
        - recipient: age14x7jgxf0t2dfmquw6cenec5c7lqryzcvd0cxv85xlwtzafdcr9eql0vmm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcGwrRllFbW5xSGoyVVJx
            ZnU0bFZDWXhjcDUwTHEwa3JpZWpvdkxFNDJrCjNWRDhWdUZGZ1NFTmFUeUg2dS95
            enFQN0ZZbEFCU204QTU5QjJjTnBvZ3cKLS0tIEFOdDRVN0RieVJRVzlsNnhHYXNo
            WG1uZ3B4eWNTNVFrREMxR3UvU1NtcUUKt4EdMs092yK+PybAFUHspDgNz6eHWyw1
            Y5TFJaMytROlAFiM3fqrU+QfFkUcw9gFv+I3xg/D1lUk1N3q9yJ+eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T11:35:37Z"
    mac: ENC[AES256_GCM,data:XjCtCQGoPn7SVTJZTBVIPLGKEwzs5UDNlHuBH8Yua1YZd9NxqLFtW2unmqxFSO1JC+WDWQ5FK3vRwSvzm9ac1/eVRdA/466/iUB6cvZfvzCdH2sBXEHecS9zydHI+pjt8OxVFmSft2GM64SASQqjp7D0uWQs4Xi2KBp4tvDdNG0=,iv:vePhkfqTkgc4TftTOfT5MUiR40cLuk6zZyxBilwqK7w=,tag:ydbdXVikvjIcZilbXxz27A==,type:str]
    encrypted_regex: ^(secrets|.*)$
    version: 3.11.0
