apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.constants.pv }}
spec:
  capacity:
    storage: {{ .Values.constants.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-media-storage
  local:
    path: "/media"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - raspberka-ekran