apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin.pvName" . }}
spec:
  capacity:
    storage: {{ include "jellyfin.storageSize" . }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        {{- include "jellyfin.nodeSelectorTermsConfig" . | indent 8 }}