authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:JLlo36iBHyI3IeGdrEV9mcTEG7HfSfKWyd3SWp+DBJURWxwZjYPyIU1xFXqxmXABpUY=,iv:GcypAPSdvgnsYixjU5cghfAna2fkAKamVq/6L64yQT0=,tag:6bYdfiALCIf2TkjsIvi5vw==,type:str]
        postgresql:
            password: ENC[AES256_GCM,data:+oLEPoFabWnWcHcoPRgD7GjmSumz6NKfnlTdVPXFT3vjqEz3vK9DCo6WLr8nyIMi+Uo=,iv:Ti9/mFv7LcgWwpc4kTToqzqFSUsHLspZZnZ7jdfcH1Y=,tag:IBS1cUwo2Yn4+aRB3GhmTg==,type:str]
    postgresql:
        auth:
            password: ENC[AES256_GCM,data:XXPtAEVikDCknNC91c1jUYaAdqq8glPxY0i2gYjeRM4W0k4llZxh77d7dtCVYUYbA/U=,iv:2rwdK5iNloz7mnG9dpKgI+TkcZapkiZv8xFZ0Uc0ql4=,tag:rjod/kdOFjlPzTTPxdAa6g==,type:str]
sops:
    age:
        - recipient: age1vsy9s6dvp03zu0zrwflrxy3fxg8jh6rns4rjaktarnhk7u9yngvs3qmh9c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOGRDVTY1RjRoSEZKUElw
            T2l5anpHN1dRMW1xWHZXMEtHZTliZ0VwcEZBClZwcW1IMDRJT2ViTDlScXBPREF1
            MktJYi9pL3RkWFd3cTFFSVpWR3RjRG8KLS0tIHgvQXRPSGZQVVVIQ01vc0RvK1lZ
            Q1NMZ1cxRXhWRm9TTDJCWG5XOTlHTzQKmwsZkOcD077/7mByzVQNGIloEs969/hG
            ZzV/QvKHePCarrhqBU4SKX825QLNd19GGDnH45vQi37AHOKlxYocvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T21:15:18Z"
    mac: ENC[AES256_GCM,data:1LlHbpiStkI0YZesE/RvsKOe504GYdT3NW9++bNUWmCSCxGg9l+6+HTsMXTFRULk1r7K845h7NULOujXXdKy1yk0AKoaPN+rXbY3hLqUdLTrYAraoBBTr0V3zmnQm+JxUC6tCBX4QRuHZqo639tW5OctMUCvZ99C/wLKzsXFdek=,iv:HhoqTJYO3KOLvt/C1u4a2DcdwBAGWERA+T1OOxl1urs=,tag:aU68chYZHSadx9JsS+w/xA==,type:str]
    encrypted_regex: ^(secrets|.*)$
    version: 3.11.0
